[development]
address = "localhost"
port = 6969
workers = 2
log = "normal"

[staging]
address = "localhost"
port = 6969
workers = 2
log = "normal"

[production]
address = "localhost"
port = 6969
workers = 2
log = "critical"