[development]
address = "localhost"
port = 6969
workers = 2
log = "normal"
password_hash = "b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86"

[staging]
address = "localhost"
port = 6969
workers = 2
log = "normal"

[production]
address = "localhost"
port = 6969
workers = 2
log = "critical"